(set-logic ALL)
(declare-var i Int)
(declare-var x (Array Int Int))
(declare-var x! (Array Int Int))
(declare-var i! Int)
(synth-fun inv-fn((parameter0 Int)(parameter1 (Array Int Int)))Bool)
(constraint (=> (and (and (=> (and (< i 4) (>= i 0) )(= (select x i) 1)) (=> (and (< i 4) (>= i 0) )(= (select x i) 1)) (=> (and (< i 4) (>= i 0) )(= (select x i) 1)) (=> (and (< i 4) (>= i 0) )(= (select x i) 1)) ) (= i 0) )(inv-fn i x )))
(constraint (=> (and (and (and (< (+ i 1) 4) (>= (+ i 1) 0) ) (and (< (+ i 2) 4) (>= (+ i 2) 0) ) ) (and (< i 4) (>= i 0) ) )(=> (and (inv-fn i x ) (and (= (select x! (+ i 2)) (+ (select x (+ i 1)) (select x i))) (= i! (+ i 1)) ) )(inv-fn i! x! ))))
(constraint (=> (inv-fn i x )(and (=> (and (< (+ 0 1) 4) (>= (+ 0 1) 0) )(< (select x 0) (select x (+ 0 1)))) (=> (and (< (+ 1 1) 4) (>= (+ 1 1) 0) )(< (select x 1) (select x (+ 1 1)))) (=> (and (< (+ 2 1) 4) (>= (+ 2 1) 0) )(< (select x 2) (select x (+ 2 1)))) (=> (and (< (+ 3 1) 4) (>= (+ 3 1) 0) )(< (select x 3) (select x (+ 3 1)))) )))
(check-synth)
