(set-logic ALL)
(declare-var initial_1___ucld_5_data_var (Array Int Int))
(declare-var initial_4___ucld_7_data_var (Array Int Int))
(declare-var i Int)
(synth-fun synth_h ((x Int) (y Int)) Bool)
(declare-var state_1___ucld_5_data_var (Array Int Int))
(declare-var initial_9___ucld_5_data_var (Array Int Int))
(declare-var initial_11___ucld_6_count_var Int)
(declare-var state_1___ucld_7_data_var (Array Int Int))
(declare-var initial_12___ucld_7_data_var (Array Int Int))
(declare-var initial_10___ucld_8_count_var Int)
(declare-var state_1___ucld_8_count_var Int)
(declare-var state_1___ucld_6_count_var Int)
(constraint 
(not (or (and  (not (synth_h state_1___ucld_6_count_var state_1___ucld_8_count_var)) 
	(= state_1___ucld_6_count_var (+ initial_11___ucld_6_count_var 1)) 
	(synth_h initial_11___ucld_6_count_var initial_10___ucld_8_count_var) (forall ((i Int))  (=> (and (>= i 0) (< i initial_11___ucld_6_count_var)) (= (select initial_9___ucld_5_data_var i) (select initial_12___ucld_7_data_var i)))) (= state_1___ucld_8_count_var (+ initial_10___ucld_8_count_var 1)) (= state_1___ucld_7_data_var (store initial_12___ucld_7_data_var initial_10___ucld_8_count_var (+ (select initial_12___ucld_7_data_var (- initial_10___ucld_8_count_var 2)) (select initial_12___ucld_7_data_var (- initial_10___ucld_8_count_var 1))))) (= state_1___ucld_5_data_var (store initial_9___ucld_5_data_var initial_11___ucld_6_count_var (+ (select initial_9___ucld_5_data_var (- initial_11___ucld_6_count_var 2)) (select initial_9___ucld_5_data_var (- initial_11___ucld_6_count_var 1))))) (and (= (select initial_1___ucld_5_data_var 0) (select initial_4___ucld_7_data_var 0)) (= (select initial_1___ucld_5_data_var 1) (select initial_4___ucld_7_data_var 1))))	
(and  (not (forall ((i Int))  (=> (and (>= i 0) (< i state_1___ucld_6_count_var)) (= (select state_1___ucld_5_data_var i) (select state_1___ucld_7_data_var i))))) (= state_1___ucld_6_count_var (+ initial_11___ucld_6_count_var 1)) (synth_h initial_11___ucld_6_count_var initial_10___ucld_8_count_var) (forall ((i Int))  (=> (and (>= i 0) (< i initial_11___ucld_6_count_var)) (= (select initial_9___ucld_5_data_var i) (select initial_12___ucld_7_data_var i)))) (= state_1___ucld_8_count_var (+ initial_10___ucld_8_count_var 1)) (= state_1___ucld_7_data_var (store initial_12___ucld_7_data_var initial_10___ucld_8_count_var (+ (select initial_12___ucld_7_data_var (- initial_10___ucld_8_count_var 2)) (select initial_12___ucld_7_data_var (- initial_10___ucld_8_count_var 1))))) (= state_1___ucld_5_data_var (store initial_9___ucld_5_data_var initial_11___ucld_6_count_var (+ (select initial_9___ucld_5_data_var (- initial_11___ucld_6_count_var 2)) (select initial_9___ucld_5_data_var (- initial_11___ucld_6_count_var 1))))) (and (= (select initial_1___ucld_5_data_var 0) (select initial_4___ucld_7_data_var 0)) (= (select initial_1___ucld_5_data_var 1) (select initial_4___ucld_7_data_var 1))))	
(and  (not (synth_h 2 2)) (and (= (select initial_1___ucld_5_data_var 0) (select initial_4___ucld_7_data_var 0)) (= (select initial_1___ucld_5_data_var 1) (select initial_4___ucld_7_data_var 1))))	
(and  (not (forall ((i Int))  (=> (and (>= i 0) (< i 2)) (= (select initial_1___ucld_5_data_var i) (select initial_4___ucld_7_data_var i))))) (and (= (select initial_1___ucld_5_data_var 0) (select initial_4___ucld_7_data_var 0)) (= (select initial_1___ucld_5_data_var 1) (select initial_4___ucld_7_data_var 1)))))))
(check-synth)
