/*
 * program_generator.h
 *
 *  Created on: 25 Apr 2018
 *      Author: elipol
 */

#ifndef CPROVER_FASTSYNTH_PROGRAM_GENERATOR_FRONTEND_H
#define CPROVER_FASTSYNTH_PROGRAM_GENERATOR_FRONTEND_H

#include <util/cmdline.h>

/// Generates N random programs using specified command line options.
/// Programs are generated by producing a random assignment to the selector
/// variables in the synth_encodingt
/// \param cmdline command line
/// \param N number of programs to generate
int generate_programs(const cmdlinet &cmdline, std::size_t N);
void assemble_program(const cmdlinet &cmdline);

#endif /* CPROVER_FASTSYNTH_PROGRAM_GENERATOR_FRONTEND_H */
